spring:
  kafka:
    bootstrap-servers: localhost:9093
    topic:
      name: weather-topic
    consumer:
      group-id: mw-group-db
      client-id: appcons
    replication:
      factor: 1
    partition:
      number: 1
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.sql
    url: jdbc:postgresql://10.73.0.50:5432/weather
    user: mw_user
    password: dfltpwd2024
  r2dbc:
    url: r2dbc:postgresql://10.73.0.50:5432/weather
    username: mw_user
    password: dfltpwd2024
logging:
  charset:
    console: windows-1251
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: TRACE