server:
  shutdown: graceful
  port: ${SERVICE_CONSUMER_LOGGER_PORT}
spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    topic:
      name: conversion-topic
    consumer:
      group-id: mc-group-second
      client-id: appcons
    replication:
      factor: 1
    partition:
      number: 1
logging:
  charset:
    console: windows-1251
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: TRACE