app:
  request:
    timeout: 1500
    retry:
      duration: 150
      attempts: 3
  url: https://currate.ru
  path: /api/
  key: ${CURRATE_KEY}
server:
  shutdown: graceful
  port: ${SERVICE_REMOTE_CURRATE_PORT}