server:
  shutdown: graceful
  port: ${SERVICE_CONSUMER_DB_PORT}
spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    topic:
      name: conversion-topic
    consumer:
      group-id: mc-group-db
      client-id: appcons
    replication:
      factor: 1
    partition:
      number: 1
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.sql
    url: jdbc:postgresql://${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}/${DATASOURCE_BASE:-test}
    user: ${DATASOURCE_USERNAME:-test}
    password: ${DATASOURCE_PASSWORD:-secret}
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}/${DATASOURCE_BASE:-test}
    username: ${DATASOURCE_USERNAME:-test}
    password: ${DATASOURCE_PASSWORD:-secret}
logging:
  charset:
    console: windows-1251
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: TRACE